services:
  facefusion:
    image: ashleykza/facefusion:2.3.2
    restart: unless-stopped
    ports:
      - 3001:3001
#      - 8888:8888
#      - 2999:2999
#      - 8080:8080
    environment:
      VENV_PATH: /workspace/venvs/facefusion
    volumes:
      - ./workspace:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
