services:
  instantid:
    image: ashleykza/instantid:2.0.1
    restart: unless-stopped
    ports:
      - 3003:3001
#      - 8888:8888
#      - 2999:2999
#      - 8080:8080
    environment:
      VENV_PATH: /workspace/venvs/instantid
    volumes:
      - ./workspace:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
