version: "3.9"
networks:
  ollama-network:

services:
  ollama:
    image: ollama/ollama:0.1.32
    container_name: ollama
    volumes:
      - ./data:/root/.ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - 'OLLAMA_DEBUG=1'
    networks:
      - ollama-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [ gpu ]

  open-webui:
    image: ghcr.io/open-webui/open-webui:0.1.119
    container_name: open-webui
    restart: unless-stopped
    ports:
      - 3500:8080
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ollama-network