version: "3.9"
networks:
  ollama_ollama-network:
    external: true
services:
  gpt4free:
    image: hlohaus789/g4f:0.2.8.2
    container_name: gpt4free
    shm_size: 4gb
    volumes:
      - ./data:/app
    restart: unless-stopped
    ports:
      - "8999:8080"
      - "1337:1337"
      - "7900:7900"
    networks:
      - ollama_ollama-network